# Generated by Django 4.2 on 2023-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deparment', models.CharField(choices=[(0, 'Analytics'), (1, 'Finance'), (2, 'HR'), (3, 'Legal'), (4, 'Operations'), (5, 'Procurement'), (6, 'R&D'), (7, 'Sales & Marketing'), (8, 'Technology')], max_length=100, null=True)),
                ('Eduction', models.CharField(choices=[(0, 'Bachelor'), (1, 'Below Secondary'), (2, 'Master & above')], max_length=100, null=True)),
                ('Gender', models.CharField(choices=[(0, 'Female'), (1, 'Male')], max_length=100, null=True)),
                ('Recruitment_Channel', models.CharField(choices=[(0, 'other'), (1, 'Refferd'), (2, 'sourcing')], max_length=100, null=True)),
                ('No_of_Trainings', models.PositiveIntegerField(null=True)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('Previous_Year_Rating', models.PositiveIntegerField(null=True)),
                ('Length_Of_Service', models.PositiveIntegerField(null=True)),
                ('Award_won', models.PositiveIntegerField(null=True)),
                ('Average_Training_Score', models.PositiveIntegerField(null=True)),
                ('predication', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
