# Generated by Django 4.2 on 2023-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Deparment',
            field=models.PositiveIntegerField(choices=[(0, 'Analytics'), (1, 'Finance'), (2, 'HR'), (3, 'Legal'), (4, 'Operations'), (5, 'Procurement'), (6, 'R&D'), (7, 'Sales & Marketing'), (8, 'Technology')], null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Eduction',
            field=models.PositiveIntegerField(choices=[(0, 'Bachelor'), (1, 'Below Secondary'), (2, 'Master & above')], null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Recruitment_Channel',
            field=models.PositiveIntegerField(choices=[(0, 'other'), (1, 'Refferd'), (2, 'sourcing')], null=True),
        ),
    ]
