# Generated by Django 4.2 on 2023-11-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_deparment_alter_employee_eduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='predication',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Not Promoted'), (1, 'Promoted')]),
        ),
    ]
