# Generated by Django 4.2 on 2023-11-22 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_predication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Previous_Year_Rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
